package install

import (
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type IntegrationOptions struct {
	Platform   string
	ProjectDir string
	Executable string
}

func InstallIntegration(opts IntegrationOptions) ([]string, error) {
	root, executable, platform, err := integrationValues(opts)
	if err != nil {
		return nil, err
	}
	switch platform {
	case "codex":
		return InstallCodex(CodexOptions{ProjectDir: root, Executable: executable})
	case "claude":
		instructions := filepath.Join(root, "CLAUDE.md")
		settings := filepath.Join(root, ".claude", "settings.json")
		if err := updateOwnedSection(instructions, integrationInstructions("Claude Code")); err != nil {
			return nil, err
		}
		if err := installCommandHook(settings, "PreToolUse", "Bash|Read|Glob|Grep", executable, platform); err != nil {
			return nil, err
		}
		return []string{instructions, settings}, nil
	case "cursor":
		path := filepath.Join(root, ".cursor", "rules", "ravel.mdc")
		content := "---\ndescription: Use Ravel to scope non-trivial coding tasks before broad repository searches\nalwaysApply: true\n---\n\n" + instructionBody()
		return []string{path}, writeOwnedFile(path, content)
	case "vscode", "copilot":
		path := filepath.Join(root, ".github", "copilot-instructions.md")
		return []string{path}, updateOwnedSection(path, integrationInstructions("GitHub Copilot"))
	case "gemini":
		instructions := filepath.Join(root, "GEMINI.md")
		settings := filepath.Join(root, ".gemini", "settings.json")
		if err := updateOwnedSection(instructions, integrationInstructions("Gemini CLI")); err != nil {
			return nil, err
		}
		if err := installCommandHook(settings, "BeforeTool", "run_shell_command|read_file|list_directory|glob", executable, platform); err != nil {
			return nil, err
		}
		return []string{instructions, settings}, nil
	case "opencode":
		instructions := filepath.Join(root, "AGENTS.md")
		plugin := filepath.Join(root, ".opencode", "plugins", "ravel.js")
		if err := updateOwnedSection(instructions, integrationInstructions("OpenCode")); err != nil {
			return nil, err
		}
		content := "// Generated by Ravel. Project instructions in AGENTS.md provide graph context.\n" +
			"export const RavelPlugin = async () => ({\n" +
			"  \"tool.execute.before\": async (_input, output) => { output.args = { ...output.args }; },\n" +
			"});\n"
		if err := writeOwnedFile(plugin, content); err != nil {
			return nil, err
		}
		return []string{instructions, plugin}, nil
	default:
		return nil, fmt.Errorf("native project integration is unavailable for %q", opts.Platform)
	}
}

func UninstallIntegration(platform, projectDir string) ([]string, error) {
	root := projectDir
	if root == "" {
		root = "."
	}
	platform = normalizeIntegration(platform)
	switch platform {
	case "codex":
		return UninstallCodex(root)
	case "claude":
		return uninstallInstructionAndHook(filepath.Join(root, "CLAUDE.md"), filepath.Join(root, ".claude", "settings.json"), "PreToolUse")
	case "cursor":
		path := filepath.Join(root, ".cursor", "rules", "ravel.mdc")
		return []string{path}, removeOwnedFile(path)
	case "vscode", "copilot":
		path := filepath.Join(root, ".github", "copilot-instructions.md")
		return []string{path}, removeOwnedSection(path)
	case "gemini":
		return uninstallInstructionAndHook(filepath.Join(root, "GEMINI.md"), filepath.Join(root, ".gemini", "settings.json"), "BeforeTool")
	case "opencode":
		instructions := filepath.Join(root, "AGENTS.md")
		plugin := filepath.Join(root, ".opencode", "plugins", "ravel.js")
		if err := removeOwnedSection(instructions); err != nil {
			return nil, err
		}
		return []string{instructions, plugin}, removeOwnedFile(plugin)
	default:
		return nil, fmt.Errorf("native project integration is unavailable for %q", platform)
	}
}

func NativePlatforms() []string {
	return []string{"codex", "claude", "cursor", "vscode", "copilot", "gemini", "opencode"}
}

func integrationValues(opts IntegrationOptions) (string, string, string, error) {
	root := opts.ProjectDir
	if root == "" {
		root = "."
	}
	executable := opts.Executable
	if executable == "" {
		var err error
		executable, err = os.Executable()
		if err != nil {
			return "", "", "", err
		}
	}
	return root, executable, normalizeIntegration(opts.Platform), nil
}

func normalizeIntegration(platform string) string {
	platform = strings.ToLower(strings.TrimSpace(platform))
	if platform == "vs-code" || platform == "github-copilot" {
		return "vscode"
	}
	return platform
}

func instructionBody() string {
	return "When `.reporavel/graph.json` exists and a non-trivial coding task, bug investigation, or review has an unknown implementation location or change surface, run `ravel context \"<task>\"` before broad `rg`/`find` searches or opening many files. Use `ravel query` for exact symbol or path lookups, then `ravel explain` or `ravel path` for focused follow-up. Before modifying a selected shared symbol or file, use `ravel affected <target>` to find callers, tests, importers, and dependents. If source may have changed since the graph was loaded, refresh it once with `ravel update .`. Treat the graph as a map: read the returned source before editing and verify changes against source and tests. Skip graph calls for trivial known-file or local edits, or when the needed context is already loaded. Read `.reporavel/report.md` for an architecture overview. Treat inferred and unresolved relationships honestly."
}

func integrationInstructions(name string) string {
	return agentsStart + "\n## Ravel for " + name + "\n\n" + instructionBody() + "\n" + agentsEnd + "\n"
}

func installCommandHook(path, event, matcher, executable, platform string) error {
	root, err := readJSONObject(path)
	if err != nil {
		return err
	}
	hooks := objectAt(root, "hooks")
	current := withoutRavel(arrayAt(hooks, event))
	current = append(current, map[string]any{
		"matcher": matcher,
		"hooks": []any{map[string]any{
			"type":    "command",
			"command": shellQuote(executable) + " assistant-hook --platform " + platform,
		}},
	})
	hooks[event] = current
	root["hooks"] = hooks
	return writeJSONObject(path, root)
}

func uninstallInstructionAndHook(instructions, settings, event string) ([]string, error) {
	if err := removeOwnedSection(instructions); err != nil {
		return nil, err
	}
	if err := uninstallCommandHook(settings, event); err != nil {
		return nil, err
	}
	return []string{instructions, settings}, nil
}

func uninstallCommandHook(path, event string) error {
	root, err := readJSONObject(path)
	if errors.Is(err, os.ErrNotExist) {
		return nil
	}
	if err != nil {
		return err
	}
	hooks, ok := root["hooks"].(map[string]any)
	if !ok {
		return nil
	}
	remaining := withoutRavel(arrayAt(hooks, event))
	if len(remaining) == 0 {
		delete(hooks, event)
	} else {
		hooks[event] = remaining
	}
	if len(hooks) == 0 {
		delete(root, "hooks")
	}
	if len(root) == 0 {
		if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
			return err
		}
		_ = os.Remove(filepath.Dir(path))
		return nil
	}
	return writeJSONObject(path, root)
}

func writeOwnedFile(path, content string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(content), 0o644)
}

func removeOwnedFile(path string) error {
	if err := os.Remove(path); err != nil && !errors.Is(err, os.ErrNotExist) {
		return err
	}
	removeEmptyParents(filepath.Dir(path), ".")
	return nil
}
